import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/navbar";

import { Cinzel } from 'next/font/google'
import { Solway } from 'next/font/google'
import { Josefin_Sans } from "next/font/google";

const cinzel = Cinzel({
  subsets: ['latin'],
  display: 'swap',
})

const solway = Solway({
  subsets: ['latin'],
  weight: ['300', '400', '500', '700', '800'],
  display: 'swap',
})

const josefin= Josefin_Sans({
subsets:['latin'],
weight:['100','200','300','400','500','600','700'],
display:'swap'
})

export const metadata: Metadata = {
  title: "The Luxury Focus",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cinzel.className}>
      <body className={`${solway.className} ${josefin.className}`}
      >
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
